# ref: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.font_features
font_features MonoLisa-Medium +zero +ss04 +ss07 +ss08 +ss09
font_features MonoLisa-MediumItalic +zero +ss04 +ss07 +ss08 +ss09

# another way
font_family family="Oxygen Mono"
bold_font auto
italic_font auto
bold_italic_font auto

# Enable Script feature specifically
font_features MonoLisa-RegularItalic +ss02

font_size 11.0
force_ltr no

allow_remote_control yes

# BEGIN_KITTY_THEME
# include kanagawa_base.conf
include kanagawabones.conf
# END_KITTY_THEME

# background_image none
# background_image_layout centered
# background_image_linear no
# background_tint 0.0
# background_tint_gaps 1.0

editor vi

cursor none
cursor_shape block
